// Canonical department/unit list. Single source of truth for seeding.
export const DEPARTMENT_SEED: string[] = [
  "Jabatan Anestesiologi",
  "Jabatan Bedah Mulut dan Maksilofasial",
  "Jabatan Pergigian Pediatrik",
  "Jabatan Pergigian Penjagaan Khas",
  "Jabatan Psikiatri dan Kesihatan Mental",
  "Jabatan Patologi",
  "Jabatan Kerja Sosial Perubatan",
  "Jabatan Dietetik & Sajian",
  "Unit Fisioterapi",
  "Jabatan Perubatan Rehabilitasi",
  "Unit Terapi Cara Kerja",
  "Unit Terapi Pertuturan Bahasa",
  "Unit Nefrologi",
  "Jabatan Perubatan Forensik",
  "Unit Penjagaan Luka",
  "Unit Pengurusan Risiko Pekerjaan",
  "Unit Pengurusan Risiko & Survelan Klinikal",
  "Unit Medikolegal",
  "Unit Pencegahan & Kawalan Infeksi",
  "Unit Penyelidikan Klinikal",
  "Pejabat Pengarah Hospital",
  "Unit Perhubungan Awam",
  "Bahagian Perubatan",
  "Bahagian Pengurusan",
  "Unit Dasar Perubatan & Perancangan Perkhidmatan Klinikal",
  "Unit Perkembangan Profession Pakar & Pegawai Perubatan",
  "Jabatan Perubatan Am",
  "Jabatan Kecemasan & Trauma",
  "Jabatan Radiologi",
  "Jabatan Ortopedik",
  "Jabatan Pediatrik",
  "Jabatan Pembedahan",
  "Jabatan O&G",
  "Jabatan Rekod Perubatan",
  "Jabatan Farmasi",
  "Unit Kejururawatan",
  "Unit Kejuruteraan",
  "Unit Sumber Manusia",
  "Unit Penyelia Hospital",
  "Unit Kewangan & Hasil",
  "Unit Pentadbiran, Aset & Stor",
  "Unit Teknologi Maklumat",
  "Unit Perolehan & Pembangunan",
  "Unit Hal Ehwal Islam",
  "Unit Keselamatan",
  "Unit Psikologi Kaunseling",
];
